modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
[[mods]]
modId = "ultimineintegration"
version = "${file.jarVersion}"
displayName = "Ultimine Integration"
logoFile = "examplemod.png"
authors = "RoyalReject"
description = '''
Allows FTB Ultimine to be gated by various mechanics
'''
[[dependencies.ultimineintegration]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ultimineintegration]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ultimineintegration]]
modId = "ftbultimine"
mandatory = true
versionRange = "[1802.3.3-build.55,)"
ordering = "NONE"
side = "BOTH"

